Created the BlueSimple responsive nagivation
hundredlabs/react-components pull request #24
Opened 2023-03-25 09:56 UTC by mehrab-alam

2023-03-27 04:36 UTC, amezng requested changes

2023-03-27 04:36 UTC, amezng commented on marketing/src/index.js
> +  <BlueSimple />
Don't change the index.js ever

2023-03-27 04:36 UTC, amezng commented on marketing/src/sections/navigation/BlueSimple/BlueSimple.css
> +.features .features-menu-inactive {
Use context classes

2023-03-27 04:46 UTC, mehrab-alam commented on marketing/src/index.js
> +  <BlueSimple />
removed all changes from index.js

2023-03-27 04:47 UTC, mehrab-alam commented on marketing/src/sections/navigation/BlueSimple/BlueSimple.css
> +.features .features-menu-inactive {
used context classes

2023-03-29 04:05 UTC, amezng requested changes

2023-03-29 04:05 UTC, amezng commented on marketing/src/index.js
> +import BlueSimple from "./sections/navigation/BlueSimple/BlueSimple";
remove this import

2023-03-29 04:10 UTC, amezng approved these changes

2023-03-29 04:10 UTC, merged