Created segment navigation for mobile and desktop view
hundredlabs/react-components pull request #25
Opened 2023-03-25 12:26 UTC by zeeshanak23

2023-03-27 04:31 UTC, amezng requested changes

2023-03-27 04:31 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.css
> +.segment-Navigation .Nav-Btn>a {
Here don't use capital letter

2023-03-27 04:31 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.css
> +.segment-Navigation .Nav-Btn>button {
Use small letters like `nav-btn`

2023-03-27 04:31 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.jsx
> +                        <p>Personalized and real-time customer experience</p>
Don't repeat text. Use text from lorem ipsum

2023-03-27 04:31 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentProductMenu.js
> +const SegmentProductMenu = [
use small letter in the beginning for declaring constants

2023-03-29 06:43 UTC, zeeshanak23 commented
Done

2023-03-30 04:04 UTC, amezng requested changes

2023-03-30 04:04 UTC, amezng commented on marketing/src/index.js
> +import SegmentNav from "./sections/navigation/SegmentNavigation/SegmentNav";
Don't change this file ever

2023-03-30 04:04 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.css
> +.productMenu>div p {
Use context classes everywhere

2023-03-30 04:04 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.jsx
> +                                                        <>
No need to use `<>` empty tag as there is already a div

2023-03-30 04:04 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentNav.jsx
> +                                                    <>
Similary here you don't need empty tag

2023-03-30 04:04 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentResponsive.css
> +        display: none;
Why using capital `N` here ?

2023-03-30 04:04 UTC, amezng commented on marketing/src/sections/navigation/SegmentNavigation/SegmentResponsive.css
> +    }
Use context class everywhere

2023-03-31 04:27 UTC, amezng commented
This is not as per the design

2023-04-02 15:31 UTC, amezng commented
text color is not good. fix it

2023-04-03 04:24 UTC, amezng commented
There is no change to this PR, after my comment. Fix it ASAP.

2023-04-04 03:02 UTC, amezng approved these changes

2023-04-04 03:02 UTC, amezng commented on marketing/src/index.js
> +    </React.StrictMode>
Don't change this file.

2023-04-04 03:02 UTC, merged