Added some minor changes in Blue-Simple
hundredlabs/react-components pull request #5
Opened 2023-03-10 13:06 UTC by mehrab-alam

2023-03-10 13:07 UTC, amezng commented on marketing/src/sections/navigation/Blue-Simple/Blue-Simple.css
> +nav {
Use classnames instead of generic nav

2023-03-10 13:07 UTC, amezng commented on marketing/src/sections/navigation/Blue-Simple/Blue-Simple.jsx
> +                    <div>
Use `<ul>` and `<li>` elements for menu items instead of h3 tags

2023-03-10 13:08 UTC, amezng commented on marketing/src/index.css
> +  max-width: 1200px;
No need to add css in the index.css. Let it be default

2023-03-10 13:25 UTC, mehrab-alam commented on marketing/src/sections/navigation/Blue-Simple/Blue-Simple.css
> +nav {
Yes I resolve it

2023-03-10 13:36 UTC, amezng requested changes

2023-03-10 13:39 UTC, mehrab-alam commented on marketing/src/sections/navigation/Blue-Simple/Blue-Simple.jsx
>              <nav>
Yes I resolve it

2023-03-15 17:26 UTC, mehrab-alam commented on marketing/src/sections/navigation/Blue-Simple/Blue-Simple.jsx
> +                    <div>
Blue-Simple modified with <ul> and <li> elements

2023-03-15 17:28 UTC, mehrab-alam commented on marketing/src/index.css
> +  max-width: 1200px;
Removed  css from index.css

2023-03-16 12:36 UTC, merged