Add minor changes in AlloyNav
hundredlabs/react-components pull request #6
Opened 2023-03-10 13:31 UTC by sarajul430

2023-03-10 13:34 UTC, amezng requested changes

2023-03-10 13:34 UTC, amezng commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.jsx
> +
Remove extra spaces.

2023-03-10 13:34 UTC, amezng commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +nav{
add classnames instead of using generic tag for creating css rules.

2023-03-10 13:47 UTC, sarajul430 commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.jsx
> +
I have remove extra spaces

2023-03-10 13:48 UTC, sarajul430 commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +nav{
I have add className

2023-03-10 13:52 UTC, amezng requested changes

2023-03-10 13:52 UTC, amezng commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +.navbar > div:first-child{
Preferably use allow-nav

2023-03-10 14:08 UTC, sarajul430 commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +.navbar > div:first-child{
i have added className alloy-nav

2023-03-16 12:19 UTC, amezng requested changes

2023-03-16 13:11 UTC, amezng requested changes

2023-03-16 13:11 UTC, amezng commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +    margin: 49px -170px;
Use display flex

2023-03-16 13:11 UTC, amezng commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +    width: 1160px;
use max-width as 1200 px

2023-03-16 14:00 UTC, sarajul430 commented on marketing/src/sections/navigation/AlloyNav/AlloyNav.css
> +    width: 1160px;
I have  set width

2023-03-16 14:20 UTC, amezng approved these changes

2023-03-16 14:21 UTC, merged