Builded the Kong navigation clone using reactjs
hundredlabs/react-components pull request #7
Opened 2023-03-17 06:16 UTC by mehrab-alam

2023-03-18 11:44 UTC, amezng commented
@mehrab-alam fix the spelling of the title

2023-03-18 11:47 UTC, amezng requested changes
Only create the KongNav with white background

2023-03-18 11:47 UTC, amezng commented on marketing/src/img/sections/hero/Kong-img.png
Do not use Kong logo/img. Also create a folder in `/img/sections` with `navigation/KongNav` and save the images.

2023-03-18 11:47 UTC, amezng commented on marketing/src/index.css
> +  background-color: #fafbfd;
Do not change index css

2023-03-18 11:47 UTC, amezng commented on marketing/src/index.js
> + kong-nav
Seems incorrect. Why kebab case here ?

2023-03-18 11:47 UTC, amezng commented on marketing/src/sections/KongSection/KongSection.css
> +    padding-top: 20px;
Only create KongNav

2023-03-19 16:48 UTC, mehrab-alam commented on marketing/src/img/sections/hero/Kong-img.png
I resolved it and also created a folder  to save the images in the img/section folder

2023-03-19 16:49 UTC, mehrab-alam commented on marketing/src/index.css
> +  background-color: #fafbfd;
I removed the changes

2023-03-19 16:49 UTC, mehrab-alam commented on marketing/src/index.js
> + kong-nav
Removed the kabab cases

2023-03-19 16:50 UTC, mehrab-alam commented on marketing/src/sections/KongSection/KongSection.css
> +    padding-top: 20px;
I resolved it

2023-03-20 04:36 UTC, amezng requested changes

2023-03-20 04:36 UTC, amezng commented on marketing/src/sections/navigation/KongNav/KongNav.css
> +button {
Use context class for creating styles to avoid collison.

2023-03-20 04:36 UTC, amezng commented on marketing/src/sections/navigation/KongNav/KongNav.css
> +.product-menu:hover {
add context class here too

2023-03-20 04:36 UTC, amezng commented on marketing/src/sections/navigation/KongNav/KongNav.css
> +.product-menu:hover {
Also change the images folder

2023-03-20 06:30 UTC, amezng commented
redo all the changes

2023-03-20 06:30 UTC, closed without merging