Built the miro.com navigation clone using reactjs
hundredlabs/react-components pull request #9
Opened 2023-03-19 05:39 UTC by mehrab-alam

2023-03-20 04:40 UTC, amezng requested changes

2023-03-20 04:40 UTC, amezng commented on marketing/src/img/sections/hero/arrow.svg
add images in the `/img/sections/navigations/MiroNav`

2023-03-20 04:40 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNav.css
> +.container {
use context classes

2023-03-20 04:40 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNavMenu/MiroNavMenu.jsx
> +                                </p>
Use lorem ipsum text

2023-03-21 08:37 UTC, mehrab-alam commented on marketing/src/sections/navigation/MiroNav/MiroNavMenu/MiroNavMenu.jsx
> +                                </p>
Replaced the text with lorem ipsum text

2023-03-22 04:59 UTC, amezng requested changes

2023-03-22 04:59 UTC, amezng commented on marketing/src/index.js
> +    <MiroNav />
Don't make any change in the index.js ever

2023-03-22 04:59 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNav.css
> +} */
Don't have comments in your checkedin code

2023-03-22 04:59 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNav.css
> +.signUp {
Try to avoid `!important` use.

2023-03-22 04:59 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNav.css
> +    color: white !important;
Here too use context class

2023-03-22 04:59 UTC, amezng commented on marketing/src/img/sections/hero/globe.svg
Don't add image in the src directory

2023-03-22 04:59 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNavMenu/MiroNavMenu.jsx
> +                                <p>
Use array of objects

2023-03-22 08:12 UTC, amezng requested changes

2023-03-22 08:12 UTC, amezng commented on marketing/src/img/sections/hero/GrammarlyInstaller.cNJAtx70kpau7s2koi2l04g2.exe
Remove this file

2023-03-22 08:12 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNav.jsx
> +    const [isTrigger, setTrigger] = React.useState(false)
May be use `subNavExpanded`

2023-03-22 08:12 UTC, amezng commented on marketing/src/sections/navigation/MiroNav/MiroNavMenu/MiroNavMenu.css
> +.miroNavMenu .contact-sales a {
use kebab case here

2023-03-22 16:56 UTC, mehrab-alam commented on marketing/src/sections/navigation/MiroNav/MiroNavMenu/MiroNavMenu.css
> +.miroNavMenu .contact-sales a {
Used the kabab cases for `className`

2023-03-22 16:57 UTC, mehrab-alam commented on marketing/src/sections/navigation/MiroNav/MiroNav.jsx
> +    const [isTrigger, setTrigger] = React.useState(false)
replaced the isTrigger with subNavExpanded

2023-03-22 16:58 UTC, mehrab-alam commented on marketing/src/sections/navigation/MiroNav/MiroNav.css
> +    color: white !important;
Used the context classes

2023-03-30 04:13 UTC, amezng commented
Keep the background white and change the border color and then update the image

2023-03-31 04:30 UTC, amezng commented
not as per the design

2023-04-02 15:36 UTC, amezng commented
not as per the design

2023-04-03 04:38 UTC, amezng commented
See this original image and check yours
![Screenshot 2023-04-03 at 10 08 13 AM](https://user-images.githubusercontent.com/3398950/229412819-7b761227-5040-4db4-bf54-dd3218ab4509.png)

2023-04-04 03:12 UTC, merged